const aboutData = [
  {
    idx: 1,
    category: "Performance",
    categorySlug: "performance",
    slug: "novo-36l-v6",
    title: "Motor 3.6L V6",
    description:
      "Preparado para qualquer terreno, o Novo Jeep Gladiator entrega toda a força para você viver sua aventura com o motor 3.6L V6 com 284cv e torque de 347Nm.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-motor-destaque.jpg",
    alt_seo: "Destaque do Motor 3.6L V6 do Jeep Gladiator",
    title_seo: "Jeep Gladiator Motor 3.6L V6 ",
  },
  {
    idx: 2,
    category: "Performance",
    categorySlug: "performance",
    slug: "cambio-automatico",
    title: "Câmbio automático <br />de 8 marchas",
    description:
      "Pensado para otimizar a performance da sua picape, o Novo Jeep Gladiator possui câmbio automático de 8 marchas, garantindo que o motor trabalhe sempre na velocidade ideal para qualquer situação.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-cambio-at-8-marchas.jpg",
    alt_seo: "Detalhe do câmbio automático de 8 marchas do Jeep Gladiator",
    title_seo: "Jeep Gladiator Câmbio Automático de 8 Marchas",
  },
  {
    idx: 1,
    category: "Versatilidade",
    categorySlug: "versatilidade",
    slug: "capacidade-carga",
    title: "Capacidade de carga",
    description:
      "Sua aventura ainda mais completa com muita capacidade de carga. Tenha a liberdade de ir para qualquer lugar, levando tudo o que importa com espaço para até 1.000L na caçamba.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-capacidade-de-carga-features.jpg",
    alt_seo: "Picape Jeep Gladiator vermelha vista de trás, com quadriciclo na caçamba aberta em terreno arenoso",
    title_seo: "Jeep Gladiator Destaque Capacidade de Carga",
  },
  {
    idx: 2,
    category: "Versatilidade",
    categorySlug: "versatilidade",
    slug: "nada-pra-tras",
    title: "Nada fica para trás",
    description:
       "Com seu Novo Jeep Gladiator não importa o tamanho da sua bagagem. Além de 1.000L de volume de carga na caçamba, você também conta com a capacidade de reboque de 3.138kg.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-capacidade-reboque.jpg",
    alt_seo: "Jeep Gladiator rebocando eixo com quadriciclo",
    title_seo: "Jeep Gladiator Capacidade de Reboque",
  },
  {
    idx: 3,
    category: "Versatilidade",
    categorySlug: "versatilidade",
    slug: "protecao-carga",
    title: "Proteção para sua carga",
    description:
      "Proteja sua carga e carroceria sem renunciar o design robusto da sua picape. A capota marítima conserva o conteúdo da caçamba, mantendo a estética da sua picape e garantindo mais segurança e conforto para sua aventura.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-capota-maritima.jpg",
    alt_seo: "Jeep Gladiator com caçamba coberta por capota marítima",
    title_seo: "Jeep Gladiator Capota Marítima ",
  },
  {
    idx: 4,
    category: "Versatilidade",
    categorySlug: "versatilidade",
    slug: "maximize-carga",
    title: "Maximize seu espaço de carga",
    description:
      "Descubra ainda mais versatilidade com os 4 ganchos na caçamba do seu Novo Jeep Gladiator. Eles ficam nas cavidades das rodas e são ajustáveis, para maximizar ainda mais o seu espaço de carga.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-ganchos-carga.jpg",
    alt_seo: "Ganchos de carga nas cavidades das rodas na caçamba do Jeep Gladiator ",
    title_seo: "Jeep Gladiator Ganchos de Carga",
  },
  {idx: 5,
    category: "Versatilidade",
    categorySlug: "versatilidade",
    slug: "energia-aventura",
    title: "Energia para sua aventura",
    description:
      "O seu Jeep Gladiator está preparado para todos os terrenos e cenários! Nele vem instalada a tomada de 220v que fica na parte de trás da caçamba.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-tomada.jpg",
    alt_seo: "Detalhe da tomada de 115 v na caçamba do Jeep Gladiator",
    title_seo: "Jeep Gladiator Tomada 115 V",
  },
  // {
  //   idx: 6,
  //   category: "Versatilidade",
  //   categorySlug: "versatilidade",
  //   slug: "porta-mutifuncional",
  //   title: "Porta traseira multifuncional",
  //   description:
  //     "Comporte a sua carga de acordo com suas necessidades, com as 3 posições para a porta da caçamba: fechada, parcialmente aberta e aberta, facilitando no manuseio de cargas.",
  //   link: "",
  //   labelLink: "",
  //   image: "/assets/images/about/img-versatilidade-porta-traseira.jpg",
  //   alt_seo: "TESTE_ALT_SEO",
  //   title_seo: "TESTE_TITLE_SEO",
  // },
  {
    idx: 6,
    category: "Versatilidade",
    categorySlug: "versatilidade",
    slug: "seguranca-comodidade",
    title: "Segurança e comodidade",
    description:
      "Embaixo dos bancos traseiros do seu Jeep Gladiator, você conta com um porta-objetos com chave. É mais liberdade para você aproveitar suas viagens, com segurança e comodidade.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-porta-objetos.gif",
    alt_seo: "Gif do Porta-objetos sob bancos traseiros do Jeep Gladiator, primeiro com tampa fechada, em seguida, com ela aberta, com saco de dormir verde dentro, e por último aberta com uma mochila cinza e uma laranja.",
    title_seo: "Jeep Gladiator Porta-objetos",
  },
  {
    idx: 7,
    category: "Versatilidade",
    categorySlug: "versatilidade",
    slug: "feita-lavar",
    title: "Feito para lavar",
    description:
      "O interior do Novo Jeep Gladiator tem material resistente. O escoamento da água fica abaixo dos tapetes, evitando que ela fique empoçada dentro da picape.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-lavavel-escoamento.jpg",
    alt_seo: "Jeep Gladiator sendo lavado internamente, com água sendo jogada próximo ao ralo de escoamento. ",
    title_seo: "Jeep Gladiator Lavável",
  },
  {
    idx: 1,
    category: "Capacidade off-road",
    categorySlug: "capacidade-off-road",
    slug: "tracao-rock-trac",
    title: "Tração 4x4 Rock-Trac",
    description:
      "O sistema de Tração 4x4 Rock-Trac garante ao Novo Jeep Gladiator a melhor tração 4x4 do segmento. Tenha o maior controle, força em baixa velocidade e quantidade de torque disponível nas rodas. A caixa de transferência é de cinco posições, a relação reduzida é de 4:1 e o Crawl Ratio é de 77:1.\”",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-rock-trac.jpg",
    alt_seo: "Jeep Gladiator em estrada de terra",
    title_seo: "Jeep Gladiator Rock-Trac",
  },
  {
    idx: 2,
    category: "Capacidade off-road",
    categorySlug: "capacidade-off-road",
    slug: "sistema-off-road-plus",
    title: "Novo Sistema Off-road+",
    description:
      "O novo Sistema Off-Road+ ajusta automaticamente o Jeep Gladiator para qualquer tipo de terreno. Habilitado em 4HI, a calibração do veículo é ajustada para off-road de alta velocidade. O controle de tração é desativado, o controle de estabilidade pode ser desabilitado e é possível bloquear o eixo traseiro. Dessa forma, entregando performance off-road para utilização em ambientes de baixo atrito, como dunas.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-off-road-plus.jpg",
    alt_seo: "Detalhe do botão Off-Road Plus no Painel do Jeep Gladiator",
    title_seo: "Jeep Gladiator Sistema Off-Road Plus",
  },
  {
    idx: 3,
    category: "Capacidade off-road",
    categorySlug: "capacidade-off-road",
    slug: "eixos-dana-44",
    title: "Exclusivos eixos Dana® 44",
    description:
      "A robustez da picape Gladiator é encontrada em todo o carro. Os eixos dianteiros e traseiros Dana® 44 têm tubos extra grossos e forjados para resistência, rigidez e durabilidade excepcionais.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-eixos-dana-44.jpg",
    alt_seo: "Jeep Gladiator em terreno acidentado ",
    title_seo: "Jeep Gladiator Eixos Dana 44",
  },
  {
    idx: 4,
    category: "Capacidade off-road",
    categorySlug: "capacidade-off-road",
    slug: "off-road-pages",
    title: "Off-Road Pages",
    description:
      "O Off-Road Pages permite acesso em tempo real às informações de desempenho off-road através da Central Multimídia, proporcionando mais segurança em suas aventuras. Acesse dados de inclinação lateral e vertical, temperatura da transmissão, coordenadas e altitude, entre outros.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-off-road-pages.jpg",
    alt_seo: "Central Multimídia do Jeep Gladiator com tela no sistema Off-Road Pages",
    title_seo: "Jeep Gladiator Off-Road Pages",
  },
  {
    idx: 5,
    category: "Capacidade off-road",
    categorySlug: "capacidade-off-road",
    slug: "protetores",
    title: "Protetores para uso Off-Road",
    description:
      "A sua nova picape Trail Rated te dá a liberdade e segurança para se aventurar independente dos terrenos. Isso é possível com os protetores para uso off-road, com placas de aço de alta resistência, que ajudam a preservar os principais componentes da sua máquina. Conte com protetores para cárter, transmissão, caixa de transferência e tanque de combustível.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-protetores-off-road.jpg",
    alt_seo: "Jeep Gladiator em terreno rochoso acidentado",
    title_seo: "Jeep Gladiator",
  },
  {
    idx: 6,
    category: "Capacidade off-road",
    categorySlug: "capacidade-off-road",
    slug: "reboque",
    title: "Ganchos de reboque Off-Road",
    description:
      "O Novo Jeep Gladiator conta com ganchos de reboque dianteiros e traseiro para auxiliar carros com menor capacidade off-road.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-ganchos-reboque.jpg",
    alt_seo: "Detalhe do gancho de reboque do Jeep Gladiator",
    title_seo: "Jeep Gladiator Ganchos de Reboque",
  },
  // {
  //   idx: 7,
  //   category: "Capacidade off-road",
  //   categorySlug: "capacidade-off-road",
  //   slug: "pneus-uso-misto",
  //   title: "Pneus de uso misto",
  //   description:
  //     "A sua picape Trail rated tem pneus de uso misto de 33”, que oferecem área de contato com a superfície maior do que os pneus comuns e garante melhor tração e controle para seu trajeto.",
  //   link: "",
  //   labelLink: "",
  //   image: "/assets/images/about/img-capacidade-pneus-misto.jpg",
  //   alt_seo: "TESTE_ALT_SEO",
  //   title_seo: "TESTE_TITLE_SEO",
  // },
  {
    idx: 1,
    category: "Tecnologias",
    categorySlug: "tecnologias",
    slug: "central-multimidia",
    title: 'Central Multimídia 8,4”',
    description:
      "O Novo Jeep Gladiator tem uma Central Multimídia de 8,4” com sistemas Apple Carplay e Android Auto. Além de assistente de voz para realizar comandos sem tirar as mãos do volante, você também conta com um GPS que irá te guiar na sua jornada.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-central-multimidia.jpg",
    alt_seo: "Central Multimídia de 8,4 polegadas do Jeep Gladiator ",
    title_seo: "Jeep Gladiator Central Multimídia",
  },
  {
    idx: 2,
    category: "Tecnologias",
    categorySlug: "tecnologias",
    slug: "som-premium-alpine",
    title: "Som Premium Alpine",
    description:
      "A trilha sonora da sua aventura tem a qualidade premium da única picape Trail Rated com o sistema de som Alpine. São nove alto-falantes, subwoofer e amplificador de 552 watts.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-som-premium-alpine.jpg",
    alt_seo: "Detalhe dos alto-falantes Alpine de teto no interior da picape Gladiator",
    title_seo: "Jeep Gladiator Som Premium Alpine",
  },
  {
    idx: 3,
    category: "Tecnologias",
    categorySlug: "tecnologias",
    slug: "caixa-som-portatil",
    title: "Caixa de som Portátil",
    description:
      "Um dos nove alto-falantes do Novo Jeep Gladiator é removível e vira uma caixa de som portátil Bluetooth Alpine. Ela é ultra resistente à poeira e água, com porta de carregamento USB e entrada de cabo auxiliar, para você carregar o som da sua aventura por todos os caminhos.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-som-portatil.jpg",
    alt_seo: "Destaque da caixa de som portátil do Jeep Gladiator",
    title_seo: "Destaque Caixa de Som Portátil Jeep Gladiator",
  },
  {
    idx: 4,
    category: "Tecnologias",
    categorySlug: "tecnologias",
    slug: "piloto-automatico",
    title: "Piloto automático Adaptativo",
    description:
      "As viagens longas na sua picape Gladiator ficam menos cansativas e mais tranquilas com o piloto automático adaptativo, que ajuda no controle de velocidade e se adapta para manter uma distância segura entre os veículos a frente.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-piloto-automatico-adaptativo.jpg",
    alt_seo: "Detalhe dos botões do lado direito do volante do Jeep Gladiator ",
    title_seo: "Jeep Gladiator Piloto Automático Adaptativo",
  },
  {
    idx: 5,
    category: "Tecnologias",
    categorySlug: "tecnologias",
    slug: "quadro-instrumentos",
    title: "QUADRO DE INSTRUMENTOS DE 7\”",
    description:
      "Acesse as principais informações sobre seu Jeep Gladiator no painel de instrumentos digital de 7\". É possível customizá-lo para mostrar dados como quilometragem e velocidade.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-painel-de-instrumentos-digital.jpg",
    alt_seo: "Detalhe do Painel de Instrumentos Digital de 7 polegadas do Jeep Gladiator",
    title_seo: "Painel de Instrumentos Digital do Jeep Gladiator",
  },
  // {
  //   idx: 5,
  //   category: "Tecnologias",
  //   categorySlug: "tecnologias",
  //   slug: "park-assist",
  //   title: "Park Assist",
  //   description:
  //     "Conforto e segurança vão junto na sua aventura. Com tecnologias de radar, câmeras e sensores localizados no veículo, a sua picape Gladiator calcula as manobras necessárias para estacionar o carro na vaga desejada.",
  //   link: "",
  //   labelLink: "",
  //   image: "/assets/images/about/img-tecnologia-park-assist.jpg",
  //   alt_seo: "TESTE_ALT_SEO",
  //   title_seo: "TESTE_TITLE_SEO",
  // },
  {
    idx: 1,
    category: "Conforto",
    categorySlug: "conforto",
    slug: "ar-condicionado",
    title: "Ar-condicionado Dual-zone",
    description:
      "Liberdade é não renunciar o conforto da sua aventura. O Novo Jeep Gladiator tem o ar-condicionado com tecnologia Dual-Zone, que permite que motorista e passageiro escolham sua temperatura ideal, de forma separada e inteligente. ",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-ar-condicionado-dual-zone.jpg",
    alt_seo: "Interior do Jeep Gladiator com correntes de ar destacadas simulando ar-condicionado",
    title_seo: "Ar-condicionado Dual-zone Jeep Gladiator",
  },
  {
    idx: 2,
    category: "Conforto",
    categorySlug: "conforto",
    slug: "remote-start",
    title: "Remote Start e Keyless <br />Enter'n Go",
    description:
      "Mais praticidade com a opção de iniciar o carro sem precisar inserir a chave na ignição. A sua nova picape Jeep Gladiator te dá a liberdade para começar sua aventura apertando apenas um botão.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-keyless-enter-n-go.jpg",
    alt_seo: "Detalhe de botão de início do carro sem chave",
    title_seo: "Jeep Gladiator Keyless Enter N Go e Remote Start",
  },
  {
    idx: 3,
    category: "Conforto",
    categorySlug: "conforto",
    slug: "monitoramento-pneus",
    title: "Monitoramento <br />da pressão dos pneus",
    description:
      "O Novo Jeep Gladiator te permite manter o foco na sua aventura tendo a certeza de mais segurança com as informações sobre os pneus no cluster digital.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-painel-pressao-pneus.jpg",
    alt_seo: "Detalhe do cluster digital do Jeep Gladiator com destaque para Monitoramento da pressão de pneus",
    title_seo: "Monitoramento da pressão dos Pneus Jeep Gladiator",
  },
  {
    idx: 1,
    category: "Segurança",
    categorySlug: "seguranca",
    slug: "aviso-colisao",
    title: "Aviso de colisão frontal<br /> com frenagem de emergência",
    description:
      "Diminua ainda mais o risco de acidentes com o sistema de aviso de colisão frontal com frenagem de emergência, que consegue detectar através de sensores a presença de outros veículos, evitando acidentes e colisões, através de um aviso sonoro/visual.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-colisão-frontal.jpg",
    alt_seo: "Jeep Gladiator visto de cima, com arcos demonstrando o sensor de colisão frontal",
    title_seo: "Colisão Frontal Jeep Gladiator",
  },
  {
    idx: 2,
    category: "Segurança",
    categorySlug: "seguranca",
    slug: "monitoramento-ponto-cegos",
    title: "Monitoramento de pontos cegos",
    description:
      "O Novo Jeep Gladiator conta com o sistema de monitoramento de ponto cego, que garante mais segurança ao identificar através de sensores a presença de pedestres ou veículos fora do alcance de visão, enviando uma notificação ao condutor.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-pontos-cegos.jpg",
    alt_seo: "Jeep Gladiator visto de frente, com arcos demonstrando o sensor de pontos cegos",
    title_seo: "Monitoramento Pontos Cegos Jeep Gladiator",
  },
  {
    idx: 3,
    category: "Segurança",
    categorySlug: "seguranca",
    slug: "detector-trafego-cruzado",
    title: "Detector de tráfego cruzado",
    description:
      "O seu Jeep Gladiator tem sensores de tráfego cruzado, que possibilitam detectar movimentos de outros veículos, emitindo sinal sonoro e luminoso até que esteja seguro manobrar a picape de ré.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-trafego-cruzado.jpg",
    alt_seo: "Jeep Gladiator visto de cima, com arcos demonstrando o detector de tráfego cruzado",
    title_seo: "Detector de Tráfego Cruzado Jeep Gladiator",
  },
  {
    idx: 4,
    category: "Segurança",
    categorySlug: "seguranca",
    slug: "airbags",
    title: "Airbags frontais e laterais",
    description:
      "Além dos Airbags frontais, o seu Jeep Gladiator também conta com a proteção nas laterais. Mesmo sem as portas, todos os passageiros ficam seguros, já que os Airbags estilo cortina estão acoplados na coluna do carro.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-airbags.jpg",
    alt_seo: "Estrutura do Jeep Gladiator com destaque para airbags frontais e nas colunas laterais ",
    title_seo: "Airbags frontais e laterais Jeep Gladiator",
  },
  {
    idx: 5,
    category: "Segurança",
    categorySlug: "seguranca",
    slug: "assistente-partida",
    title: "Assistente de Partida em Rampa",
    description:
      "Com o Assistente de Partida em Rampa (HSA), a sua picape Jeep Gladiator te dá ainda mais segurança em ladeiras, garantindo que sua aventura continue seguindo sempre adiante.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-assistente-partida-rampa.jpg",
    alt_seo: "Jeep Gladiator vermelho em aclive.",
    title_seo: "Assistente de Partida em Rampa Jeep Gladiator",
  },
  // {
  //   idx: 6,
  //   category: "Segurança",
  //   categorySlug: "seguranca",
  //   slug: "controle-eletronico",
  //   title: "Controle Eletrônico<br /> de Alcance e de Estabilidade",
  //   description:
  //     "O Novo Jeep Gladiator vem preparada para te dar mais segurança em situações extremas. Conte com as tecnologias de Controle Eletrônico de Alcance (ERS), para definir a marcha mais alta para o câmbio automático, e Controle Eletrônico de Estabilidade (ESC).",
  //   link: "",
  //   labelLink: "",
  //   image: "/assets/images/about/img-seguranca-controle-eletronico.jpg",
  //   alt_seo: "TESTE_ALT_SEO",
  //   title_seo: "TESTE_TITLE_SEO",
  // },
  {
    idx: 1,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "acessorios-disponiveis",
    title: "Mais de 70 acessórios disponíveis",
    description:
      "Eleve ainda mais sua experiência off-road com os mais de 70 acessórios disponíveis para o seu Novo Jeep Gladiator. Tenha a essência do Open-air com tube doors, barras transversais, suporte para bicicleta e muito mais.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-acessórios.jpg",
    alt_seo: "Jeep Gladiator visto de cima com acessórios como suporte para bicicleta",
    title_seo: "Acessórios Jeep Gladiator",
  },
  {
    idx: 2,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "estribo-lateral",
    title: "Estribo lateral",
    description:
      "Estribos laterais adicionam funcionalidade e estilo ao seu Novo Jeep Gladiator. Estes estribos laterais pretos foram moldados para fornecer maior facilidade no acesso e saída do veículo.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-estribo-lateral.jpg",
    alt_seo: "Estribos laterais para Jeep Gladiator em fundo branco",
    title_seo: "Estribo Lateral Jeep Gladiator",
  },
  {
    idx: 3,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "grade-frontal-preta",
    title: "Grade Frontal Preta",
    description:
      "Grade dianteira em preto satino que ressalta ainda mais a aparência off-road do seu Novo Jeep Gladiator.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-grade-frontal.jpg",
    alt_seo: "Detalhe da frente do Jeep Gladiator, com grade frontal preta",
    title_seo: "Grade Frontal Jeep Gladiator",
  },
  {
    idx: 4,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "portas-tubulares",
    title: "Portas Tubulares",
    description:
      "As portas tubulares são construídas com tubos de aço de 2\". O kit inclui as quatro portas com dobradiças e travas.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-portas-tubulares.jpg",
    alt_seo: "Portas tubulares feitas com tubos de aço no Jeep Gladiator vermelho ",
    title_seo: "Portas Tubulares Jeep Gladiator",
  },
  {
    idx: 5,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "armazenagem-cacamba",
    title: "Sistema armazenagem na caçamba",
    description:
      "Organize sua carga com esta caixa de ferramentas inteligente e ergonômica. O sistema inclui duas gavetas à prova de intempéries que deslizam para fora da caçamba e permitem armazenar praticamente qualquer coisa.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-organizador-cacamba.jpg",
    alt_seo: "Gavetas organizadoras para a caçamba do Jeep Gladiator.",
    title_seo: "Organizador de Caçamba Jeep Gladiator",
  },
  {
    idx: 6,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "tapetes-bordas-elevadas",
    title: "Tapetes bordas elevadas",
    description:
      "Os tapetes de bordas elevadas são projetados para fornecer cobertura máxima e proteger seu piso da umidade, neve, lama e sujeira. Este conjunto de tapetes com design e estilo off-road tem encaixe perfeito no seu Novo Jeep Gladiator, permitindo a drenagem sem remover o tapete.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-tapetes-bordas-elevadas.jpg",
    alt_seo: "Tapetes de bordas elevadas preto com detalhe da marca em vermelho para o Jeep Gladiator",
    title_seo: "Tapetes Bordas Elevadas Jeep Gladiator",
  },
  {
    idx: 7,
    category: "Acessórios",
    categorySlug: "acessorios",
    slug: "suporte-bicicleta",
    title: "Suporte de Bicicleta",
    description:
      "O suporte de bicicleta possui função auto-ajuste para fixação. Acomoda quadros de bicicleta de até 21“ no seu Novo Jeep Gladiator.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-suporte-bicicleta.jpg",
    alt_seo: "Suporte de bicicleta para o Jeep Gladiator",
    title_seo: "Suporte de bicicleta Jeep Gladiator",
  },
  {
    idx: 1,
    category: "Serviços e garantia",
    categorySlug: "servicos-garantia",
    slug: "pacotes-manutencao",
    title: "Pacotes de Manutenção",
    description:
      "Adquira um dos Pacotes de Manutenção customizáveis junto com o seu Jeep. Tranquilidade e segurança com peças e serviços Mopar, além de pagamento flexibilizado ao longo do ciclo de uso do seu Novo Jeep Gladiator. Conheça os pacotes na concessionária de sua preferência.",
    link: "",
    labelLink: "",
    image: "/assets/images/about/Jeep-gladiator-revisao.png",
    alt_seo: "Mulher branca, de cabelo liso escuro, dentro de um carro, com porta aberta mostrando tela do computador para homem branco e careca, que está do lado de fora.",
    title_seo: "Revisão Jeep Gladiator",
  },
  {
    idx: 2,
    category: "Serviços e garantia",
    categorySlug: "servicos-garantia",
    slug: "garantia-adicional",
    title: "Garantia Adicional",
    description:
      "O seu Novo Jeep Gladiator pode ter até 5 anos de garantia. São planos de 12 ou 24 meses adicionais a garantia de fábrica. Economia para você e seu Jeep protegido por mais tempo.",
    link: "https://www.jeep.com.br/proprietarios/pacote-de-servicos.html",
    labelLink: "Saiba mais",
    image: "/assets/images/about/Jeep-gladiator-garantia.png",
    alt_seo: "Mulher negra, de cabelo castanho claro crespo, de camisa branca, mostra tela do computador sobre a mesa para rapaz negro, de cabelo castanho escuro crespo, de jaqueta verde, sentado do outro lado do móvel",
    title_seo: "Garantia Jeep Gladiator",
  },
];

export default aboutData;
