const galleryData = [
  {
    slug: "image-01",
    thumb: "/assets/images/Jeep-gladiator-terreno-rochoso-thumb.jpg",
    mobile: "/assets/images/Jeep-gladiator-terreno-rochoso-mobile.jpg",
    preview: "/assets/images/Jeep-gladiator-terreno-rochoso-preview.jpg",
    full: "/assets/images/Jeep-gladiator-terreno-rochoso-full.jpg",
    alt_seo: "Jeep Gladiator em terreno rochoso",
    title_seo: "Jeep Gladiator",
  },
  {
    slug: "image-02",
    thumb: "/assets/images/Jeep-gladiator-interior-thumb.jpg",
    mobile: "/assets/images/Jeep-gladiator-interior-thumb-mobile.jpg",
    preview: "/assets/images/Jeep-gladiator-interior-preview.jpg",
    full: "/assets/images/Jeep-gladiator-interior-full.jpg",
    alt_seo: "Interior do Jeep Gladiator com painel vermelho, com detalhes vermelho e bancos de couro preto.",
    title_seo: "Jeep Gladiator Interior",
  },
  {
    slug: "image-03",
    thumb: "/assets/images/Jeep-gladiator-bancos-traseiros-thumb.jpg",
    mobile: "/assets/images/Jeep-gladiator-bancos-traseiros-thumb-mobile.jpg",
    preview: "/assets/images/Jeep-gladiator-bancos-traseiros-preview.jpg",
    full: "/assets/images/Jeep-gladiator-bancos-traseiros-full.jpg",
    alt_seo: "Bancos traseiros de couro preto do Jeep Gladiator",
    title_seo: "Jeep Gladiator Bancos Traseiros",
  },
  {
    slug: "image-04",
    thumb: "/assets/images/Jeep-gladiator-som-premium-alpine-galeria-thumb.jpg",
    mobile: "/assets/images/Jeep-gladiator-som-premium-alpine-galeria-thumb-mobile.jpg",
    preview: "/assets/images/Jeep-gladiator-som-premium-alpine-galeria-preview.jpg",
    full: "/assets/images/Jeep-gladiator-som-premium-alpine-galeria-full.jpg",
    alt_seo: "Detalhe dos alto-falantes Alpine de teto no interior da picape Gladiator",
    title_seo: "Jeep Gladiator Som Premium Alpine",
  },
  {
    slug: "image-05",
    thumb: "/assets/images/Jeep-gladiator-motos-cacamba-thumb.jpg",
    mobile: "/assets/images/Jeep-gladiator-motos-cacamba-thumb-mobile.jpg",
    preview: "/assets/images/Jeep-gladiator-motos-cacamba-preview.jpg",
    full: "/assets/images/Jeep-gladiator-motos-cacamba-full.jpg",
    alt_seo: "Traseira do Jeep Gladiator com duas motos na caçamba com porta traseira aberta ",
    title_seo: "Motos na Caçamba do Jeep Gladiator",
  },
  {
    slug: "image-06",
    thumb: "/assets/images/Jeep-gladiator-badge-trail-rated-galeria-thumb.jpg",
    mobile: "/assets/images/Jeep-gladiator-badge-trail-rated-galeria-thumb-mobile.jpg",
    preview: "/assets/images/Jeep-gladiator-badge-trail-rated-galeria-preview.jpg",
    full: "/assets/images/Jeep-gladiator-badge-trail-rated-galeria-full.jpg",
    alt_seo: "Detalhe do Badge Trail Rated na lateral do Jeep Gladiator ",
    title_seo: "Jeep Gladiator Badge Trail Rated",
  },
  {
    slug: "image-07",
    thumb: "/assets/images/Jeep-gladiator-camera-off-road-trailcam-galeria-thumb.jpg",
    mobile: "/assets/images/Jeep-gladiator-camera-off-road-trailcam-galeria-thumb-mobile.jpg",
    preview: "/assets/images/Jeep-gladiator-camera-off-road-trailcam-galeria-preview.jpg",
    full: "/assets/images/Jeep-gladiator-camera-off-road-trailcam-galeria-full.jpg",
    alt_seo: "Detalhe frontal do Jeep Gladiator com câmera Off Road Trailcam na grade",
    title_seo: "Jeep Gladiator Câmera Off Road Trailcam",
  },
  {
    slug: "image-08",
    thumb: "/assets/images/Jeep-gladiator-interior-painel-thumb.jpg",
    mobile: "/assets/images/Jeep-gladiator-interior-painel-thumb-mobile.jpg",
    preview: "/assets/images/Jeep-gladiator-interior-painel-preview.jpg",
    full: "/assets/images/Jeep-gladiator-interior-painel-full.jpg",
    alt_seo: "Interior do Jeep Gladiator com painel vermelho, com detalhes vermelho.",
    title_seo: "Jeep Gladiator Interior",
  },
];

export default galleryData;
