const highlightData = [
  {
    slug: "destaque-1",
    title: "",
    titleMobile: "",
    description: "",
    label: "aqui label",
    tag: "",
    thumb: "",
    image: "/assets/images/highlight/Jeep-gladiator-vermelho-home.jpg",
    imageMobile: "/assets/images/highlight/Jeep-gladiator-vermelho-home-mobile.jpg",
    link: "",
    alt_seo: "Vista Lateral da picape Jeep Gladiator vermelha em terreno rochoso",
    title_seo: "Jeep Gladiator Vermelho",
  },
  {
    slug: "destaque-2",
    title: "Tração 4x4 Rock-Trac",
    titleMobile: "Tração 4x4 <br />Rock-Trac",
    description:
    "O Novo Jeep Gladiator é feito para qualquer terreno. Ele tem a melhor tração 4x4 do segmento para você contar com força máxima e maior controle de direção nas suas aventuras.",
    label: "Tração 4x4",
    subTitle: "Rock-Trac",
    tag: "tracao",
    thumb: "/assets/images/highlight/Jeep-gladiator-vermelho-tracao-rock-trac-thumb.jpg",
    image: "/assets/images/highlight/Jeep-gladiator-vermelho-tracao-rock-trac.jpg",
    imageMobile: "/assets/images/highlight/Jeep-gladiator-vermelho-tracao-rock-trac-mobile.jpg",
    link: "",
    alt_seo: "Picape Jeep Gladiator vermelha vista de cima em terreno arenoso",
    title_seo: "Jeep Gladiator Tração 4x4 Rock-Trac",
  },
  {
    slug: "destaque-3",
    title: "Open-air experience",
    titleMobile: "Open-air experience",
    description:
    "Para quem curte apreciar a natureza de perto, conte com a praticidade do teto e das portas removíveis, além do para-brisa rebatível que permite alcançar a verdadeira essência Open-Air.",
    label: "Open-Air",
    subTitle: "Experience",
    tag: "open-air",
    thumb: "/assets/images/highlight/Jeep-gladiator-vermelho-open-air-thumb.jpg",
    image: "/assets/images/highlight/Jeep-gladiator-vermelho-open-air.jpg",
    imageMobile: "/assets/images/highlight/Jeep-gladiator-vermelho-open-air-mobile.jpg",
    link: "",
    alt_seo: "Picape Jeep Gladiator vermelha sem portas e tetos e com o para-brisa rebatido",
    title_seo: "Jeep Gladiator Open Air Experience",
  },
  {
    slug: "destaque-4",
    title: "Carga e reboque",
    titleMobile: "Carga <br />e reboque",
    description:
    "Com volume de carga de até 1.000l e com capacidade de reboque de até 3.138kg, o novo Jeep Gladiator te dá liberdade para ir para qualquer lugar sem precisar deixar nada para trás.",
    label: "Carga",
    subTitle: "e reboque",
    tag: "carga-reboque",
    thumb: "/assets/images/highlight/Jeep-gladiator-vermelho-capacidade-carga-thumb.jpg",
    image: "/assets/images/highlight/Jeep-gladiator-vermelho-capacidade-carga.jpg",
    imageMobile: "/assets/images/highlight/Jeep-gladiator-vermelho-capacidade-carga-mobile.jpg",
    link: "",
    alt_seo: "Picape Jeep Gladiator vermelha vista de trás, com quadriciclo na caçamba aberta",
    title_seo: "Jeep Gladiator Capacidade de Carga",
  },
  {
    slug: "destaque-5",
    title: "Tecnologias<br /> semiautônomas",
    titleMobile: "Tecnologias <br /> semiautônomas",
    description:
    "Encare os obstáculos de frente. A picape Gladiator vem equipada com tecnologias semiautônomas como piloto automático adaptativo e monitoramento de pontos cegos.",
    label: "Tecnologias",
    subTitle: "semiautônomas",
    tag: "tecnologias-semiautonomas",
    thumb: "/assets/images/highlight/Jeep-gladiator-prata-tecnologias-thumb.jpg",
    image: "/assets/images/highlight/Jeep-gladiator-prata-tecnologias.jpg",
    imageMobile: "/assets/images/highlight/Jeep-gladiator-prata-tecnologias-mobile.jpg",
    link: "",
    alt_seo: "Jeep Gladiator visto de frente, com arcos demonstrando o sensor de pontos cegos",
    title_seo: "Jeep Gladiator Tecnologias Semiautônomas",
  },
];

export default highlightData;
